# Generated by Django 3.1.4 on 2020-12-06 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store_email_stu_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(max_length=100)),
                ('Student_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='store_email_teach_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_ID', models.CharField(max_length=100)),
                ('Teacher_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_login_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_ID', models.CharField(max_length=50)),
                ('Teacher_Name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=300)),
                ('Teacher_pass', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student_login_inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(max_length=50)),
                ('Student_Name', models.CharField(max_length=255)),
                ('Student_pass', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.teacher_login_information')),
            ],
        ),
        migrations.CreateModel(
            name='student_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_group_name', models.CharField(max_length=10)),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_login_inform')),
            ],
        ),
    ]
