# Generated by Django 3.1.4 on 2020-12-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_login_infor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_ID', models.CharField(max_length=50)),
                ('Teacher_Name', models.CharField(max_length=255)),
                ('Teacher_pass', models.CharField(max_length=255)),
            ],
        ),
    ]
