# Generated by Django 3.1.4 on 2020-12-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_teacher_login_infor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_login_infor',
        ),
    ]
