# Generated by Django 3.1.4 on 2020-12-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_student_login_informa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_groups',
            name='Student_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_login_informa'),
        ),
        migrations.DeleteModel(
            name='Student_login_inform',
        ),
    ]
