# Generated by Django 3.1.4 on 2020-12-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_teacher_login_informa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_login_information',
        ),
    ]
