# Generated by Django 3.1.4 on 2020-12-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_student_courses_with_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_login_informa',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_courses_with_teacher_name'),
        ),
        migrations.DeleteModel(
            name='Student_course_with_Teacher_name',
        ),
    ]
