# Generated by Django 3.1.4 on 2020-12-07 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_auto_20201207_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_course_with_Teacher_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('Teacher_ID', models.CharField(max_length=200)),
                ('Teacher_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='student_login_informa',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_course_with_teacher_name'),
        ),
    ]
