# Generated by Django 3.1.4 on 2020-12-07 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_student_login_informatn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_groups',
            name='Student_ID',
        ),
        migrations.RemoveField(
            model_name='student_login_informa',
            name='course',
        ),
        migrations.DeleteModel(
            name='Student_course_with_Teacher_name',
        ),
        migrations.DeleteModel(
            name='student_groups',
        ),
        migrations.DeleteModel(
            name='Student_login_informa',
        ),
    ]
