# Generated by Django 3.1.4 on 2020-12-07 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_auto_20201207_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 12, 45, 49, 873084))),
                ('due_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 12, 45, 49, 873084))),
                ('title', models.CharField(max_length=500)),
                ('Details', models.CharField(max_length=500)),
                ('attachment', models.FileField(upload_to='uploads/files')),
                ('resource', models.CharField(max_length=500)),
                ('posts', models.CharField(max_length=500)),
            ],
        ),
    ]
