# Generated by Django 3.1.4 on 2020-12-07 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0014_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 18, 26, 21, 339385))),
                ('due_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 18, 26, 21, 339385))),
                ('title', models.CharField(max_length=500)),
                ('Details', models.TextField(max_length=500)),
                ('attachment', models.FileField(upload_to='uploads/files')),
                ('Image_Upload', models.ImageField(blank=True, null=True, upload_to='uploads/img')),
                ('resource', models.CharField(max_length=500)),
                ('posts', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 18, 26, 21, 339385)),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 18, 26, 21, 339385)),
        ),
    ]
