# Generated by Django 3.1.4 on 2020-12-07 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0015_auto_20201207_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload_file',
        ),
        migrations.AlterField(
            model_name='assignment_upload_file',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 18, 28, 2, 838928)),
        ),
        migrations.AlterField(
            model_name='assignment_upload_file',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 18, 28, 2, 838928)),
        ),
    ]
