# Generated by Django 3.1.4 on 2020-12-07 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0017_auto_20201207_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment_upload_file',
        ),
        migrations.AlterField(
            model_name='assignment_upload_file_image',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 18, 48, 25, 968864)),
        ),
        migrations.AlterField(
            model_name='assignment_upload_file_image',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 18, 48, 25, 968864)),
        ),
    ]
