# Generated by Django 3.1.4 on 2020-12-07 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0019_auto_20201207_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='uploads/stu_assignment_doc')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment_upload_file_image',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 19, 52, 10, 319216)),
        ),
        migrations.AlterField(
            model_name='assignment_upload_file_image',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 19, 52, 10, 319216)),
        ),
    ]
