# Generated by Django 3.1.4 on 2020-12-07 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0023_auto_20201207_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_upload_file_image',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 22, 23, 41, 707054)),
        ),
        migrations.AlterField(
            model_name='assignment_upload_file_image',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 22, 23, 41, 707054)),
        ),
        migrations.DeleteModel(
            name='Submit_Assignment_student',
        ),
    ]
