# Generated by Django 3.1.4 on 2020-12-07 17:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0027_auto_20201207_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 23, 5, 22, 395420)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 23, 5, 22, 396419)),
        ),
        migrations.CreateModel(
            name='Teacher_Assignment_upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignment_name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 23, 5, 22, 396419))),
                ('due_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 23, 5, 22, 396419))),
                ('title', models.CharField(max_length=500)),
                ('Details', models.TextField(max_length=500)),
                ('attachment', models.FileField(upload_to='uploads/files')),
                ('resource', models.CharField(max_length=500)),
                ('posts', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student_courses_with_teacher_name')),
            ],
        ),
    ]
