# Generated by Django 3.1.4 on 2020-12-07 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0029_auto_20201207_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 23, 47, 39, 738421)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 23, 47, 39, 738421)),
        ),
        migrations.DeleteModel(
            name='Teacher_Assignment_upload_file',
        ),
    ]
