# Generated by Django 3.1.4 on 2020-12-08 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0033_auto_20201208_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_Assignment_upload_file_image_detail',
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 10, 29, 57, 292308)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 10, 29, 57, 292308)),
        ),
    ]
