# Generated by Django 3.1.4 on 2020-12-08 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0035_auto_20201208_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='attachment',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 11, 11, 45, 870287)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 11, 11, 45, 870287)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 11, 11, 45, 869288)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 11, 11, 45, 869288)),
        ),
    ]
