# Generated by Django 3.1.4 on 2020-12-08 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0036_auto_20201208_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='attachment',
            field=models.FileField(upload_to='uploads/files'),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 11, 19, 35, 668600)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 11, 19, 35, 668600)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 11, 19, 35, 667601)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 11, 19, 35, 667601)),
        ),
    ]
