# Generated by Django 3.1.4 on 2020-12-08 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0037_auto_20201208_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Assignment_upload_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignment_name', models.CharField(max_length=500)),
                ('course', models.CharField(max_length=500)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 12, 9, 27, 478901))),
                ('due_date', models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 12, 9, 27, 478901))),
                ('title', models.CharField(max_length=500)),
                ('Details', models.TextField(max_length=500)),
                ('attachment', models.CharField(max_length=1000)),
                ('resource', models.CharField(max_length=500)),
                ('posts', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 12, 9, 27, 477902)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 12, 9, 27, 477902)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 12, 9, 27, 476903)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file_image',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 12, 9, 27, 476903)),
        ),
    ]
