# Generated by Django 3.1.4 on 2020-12-08 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0039_auto_20201208_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_submit_assignment',
            name='Assignment_name',
        ),
        migrations.RemoveField(
            model_name='student_submit_assignment',
            name='Student_ID',
        ),
        migrations.RemoveField(
            model_name='student_submit_assignment',
            name='course',
        ),
        migrations.DeleteModel(
            name='Teacher_Assignment_upload_file',
        ),
        migrations.RemoveField(
            model_name='teacher_assignment_upload_file_image',
            name='course',
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 15, 30, 13, 464153)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 15, 30, 13, 464153)),
        ),
        migrations.DeleteModel(
            name='Student_Submit_Assignment',
        ),
        migrations.DeleteModel(
            name='Teacher_Assignment_upload_file_image',
        ),
    ]
