# Generated by Django 3.1.4 on 2020-12-08 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0041_auto_20201208_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 44, 10, 499830)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 44, 10, 499830)),
        ),
        migrations.DeleteModel(
            name='Assignment_Comments',
        ),
    ]
