# Generated by Django 3.1.4 on 2020-12-08 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0043_auto_20201208_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 49, 11, 941182)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 49, 11, 941182)),
        ),
        migrations.DeleteModel(
            name='Assignment_Comment',
        ),
    ]
