# Generated by Django 3.1.4 on 2020-12-08 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0045_auto_20201208_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_comment',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 51, 34, 730927)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 51, 34, 728929)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 51, 34, 728929)),
        ),
    ]
