# Generated by Django 3.1.4 on 2020-12-08 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0046_auto_20201208_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_comment',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 54, 33, 939215)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 54, 33, 937218)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 54, 33, 937218)),
        ),
        migrations.CreateModel(
            name='Assignment_Comments',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('postID', models.CharField(max_length=255)),
                ('time_comment', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 54, 33, 939215))),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.assignment_comments')),
            ],
        ),
    ]
