# Generated by Django 3.1.4 on 2020-12-08 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0047_auto_20201208_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment_Comment',
        ),
        migrations.AlterField(
            model_name='assignment_comments',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 56, 0, 229313)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 56, 0, 227314)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_files',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 16, 56, 0, 227314)),
        ),
    ]
