# Generated by Django 3.1.4 on 2020-12-08 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0049_auto_20201208_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_Assignment_upload_Files',
        ),
        migrations.AlterField(
            model_name='assignment_comments',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 22, 45, 44, 655076)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 22, 45, 44, 653078)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 8, 22, 45, 44, 653078)),
        ),
    ]
